[package]
name = "mycrate"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext.git" }

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 1
